
window.PORTFOLIO = {
  profile: {name:'Harsha Vardhan A S', register:'1115252033', department:'Artificial Intelligence & Machine Learning', year:'2nd year', email:'25al033@rmd.ac.in', college:'R.M.D. Engineering College'},
  intro:'AI & ML student exploring the intersection of intelligent systems and practical software. Building skills in Java, full-stack development, and machine learning.',
  objectives: {short:'Strengthen my programming and machine-learning foundations through hands-on projects, internships, and consistent problem-solving practice.',long:'Build a career in software and AI development, creating useful, reliable applications that solve everyday problems.'},
  academic: {degree:'B.Tech · Artificial Intelligence & Machine Learning', dates:'September 2025 – Present', score:'7.8', scoreNote:'Score listed in résumé; grading scale and semester to be added.', school:'Velammal Vidyalaya Annexure · CBSE · Completed in 2025.'},
  skills:[{title:'Programming',items:['Java','Python','SQL']},{title:'Web development & tools',items:['HTML','CSS','Spring Boot','SQL databases']},{title:'Technical focus',items:['Artificial intelligence','Machine learning','K-Nearest Neighbours','Full-stack development']}],
  projects:[
    {title:'Disease Prediction using Machine Learning',category:'Machine learning',status:'Academic project',description:'A Python-based academic model that uses symptoms as inputs for disease classification.',tech:['Python','KNN','Machine learning'],problem:'Explore how a classification algorithm can identify patterns between symptoms and disease labels.',contribution:'Built a Python model using the K-Nearest Neighbours algorithm.',outcome:'Created an academic disease-prediction model. Dataset, validation method, and evaluation metrics to be added; not a clinical tool.'},
    {title:'Smart Water Usage Predictor',category:'AI for sustainability',status:'Concept / presentation',description:'An AI/ML concept for forecasting water consumption and identifying unusual usage.',tech:['Time-series prediction (proposed)','Anomaly detection (proposed)','IoT sensors (future scope)'],problem:'Daily water wastage and sudden changes in consumption can go unnoticed.',contribution:'Prepared the concept and presentation content for an AI/ML water-management system.',outcome:'Defined the proposed workflow: collect usage data, analyze patterns, predict demand, and issue alerts. Implementation and results are not yet documented.'}
  ],
  internship:{role:'Java Full Stack Developer',organization:'ACTE Technologies',duration:'Six months',work:'Java full-stack development internship listed in my résumé. Exact dates, assigned work, and deliverables to be added.',learning:'Detailed learning outcomes and technologies used during the internship to be added.'},
  achievements:[{title:'Technical coding competitions',text:'Participated in technical coding competitions, as listed in my résumé. Event names and results to be added.'},{title:'Academic achievements & awards',text:'Verified academic distinctions, awards, and supporting details to be added.'},{title:'Hackathons',text:'Confirmed participation, project details, and outcomes to be added.'}],
  activities:[{title:'Technical activities',text:'Academic projects in Python, SQL, and web development; participation in technical coding competitions.'},{title:'Paper presentations & events',text:'Paper titles, technical event names, and participation details to be added.'},{title:'Beyond the classroom',text:'Sports, clubs, cultural activities, and responsibilities to be added.'}],
  development:[{title:'Communication',text:'Practice explaining project decisions clearly through short presentations and written documentation.'},{title:'Leadership',text:'Develop planning and ownership skills by taking responsibility for well-defined project tasks.'},{title:'Teamwork',text:'Improve collaboration through shared tasks, constructive feedback, and dependable follow-through.'},{title:'Problem-solving',text:'Strengthen debugging and analytical thinking through regular coding practice.'}],
  future:[{title:'Career plans',text:'Pursue internships and entry-level opportunities in software development and AI/ML.'},{title:'Skills to develop',text:'Deepen Java, Python, and SQL skills; develop stronger model-evaluation, web-development, and software-testing practices.'}],
};
